### ISSUE TITLE
This will replace the current torus variables. Continue ? (y or n) y

### ISSUE THREAD

**Issue by skovuri41** [chimay/torus#10]
how to avoid this prompt on every restart of emacs? have the default configuration as in Readme.

**Comment by chimay** [comment]
this prompt shows up when a torus is read AND the current torus is not empty.

at startup, the torus should be empty before reading the torus-file, and this prompt should not be there.

my guess is : your config reads the file twice. Are you using the function (torus-read) somewhere in your init file ?

Note that there are 2 versions of torus : the default master branch contains the configuration for version 1. If you use version 2, please use the README of branch version-2.

**Comment by skovuri41** [comment]
Got it, had both variables in config
torus-dirname
toruns-autoread-file

will checkout version 2.
