### ISSUE TITLE
torus-read: Symbol’s function definition is void: subseq

### ISSUE THREAD

**Issue by vornado63** [chimay/torus#3]
I am using torus (elpa torus-20190308.1757) with the use-package (more or less) from the README.md
I added :demand, since :bind implies :defer.

This is message shows up upon loading.

**Comment by chimay** [comment]
Strange, subseq depends on cl-lib, loaded in torus.el
I’ll try to find why

**Comment by chimay** [comment]
Found it ! Some lib mess, should work now. 
It’ll be in Melpa in a few hours.
Please tell me if you still encounter some issue.

**Comment by vornado63** [comment]
ok, i ll check this tomorrow.

**Comment by vornado63** [comment]
Complaints about subseq are gone (tested with torus-20190310.1651 from elpa). :)

**Comment by chimay** [comment]
Great !
