### ISSUE TITLE
torus--update-position: Function torus--update-history : bad torus

### ISSUE THREAD

**Issue by vornado63** [chimay/torus#4]
I am using torus (elpa torus-20190308.1757) with the use-package (more or less) from the README.md

Upon closing emacs (i did not work with it or create a torus), it is not possible to close emacs because of this error:

Debugger entered--Lisp error: (error "Function torus--update-history : bad torus")
  signal(error ("Function torus--update-history : bad torus"))
  error("Function torus--update-history : bad torus")
  torus--update-position()
  torus-write("~/.emacs.d/torus/last.el")
  torus-quit()
  kill-emacs()
  #f(compiled-function (&optional arg) "Offer to save each buffer, then kill this Emacs process.\nWith prefix ARG, silently save all file-visiting buffers without asking.\nIf there are active processes where `process-query-on-exit-flag'\nreturns non-nil and `confirm-kill-processes' is non-nil,\nasks whether processes should be killed.\nRuns the members of `kill-emacs-query-functions' in turn and stops\nif any returns nil.  If `confirm-kill-emacs' is non-nil, calls it." (interactive "P") #<bytecode 0x22fe93>)(nil)
  save-buffers-kill-emacs@auto-compile(#f(compiled-function (&optional arg) "Offer to save each buffer, then kill this Emacs process.\nWith prefix ARG, silently save all file-visiting buffers without asking.\nIf there are active processes where `process-query-on-exit-flag'\nreturns non-nil and `confirm-kill-processes' is non-nil,\nasks whether processes should be killed.\nRuns the members of `kill-emacs-query-functions' in turn and stops\nif any returns nil.  If `confirm-kill-emacs' is non-nil, calls it." (interactive "P") #<bytecode 0x22fe93>) nil)
  apply(save-buffers-kill-emacs@auto-compile #f(compiled-function (&optional arg) "Offer to save each buffer, then kill this Emacs process.\nWith prefix ARG, silently save all file-visiting buffers without asking.\nIf there are active processes where `process-query-on-exit-flag'\nreturns non-nil and `confirm-kill-processes' is non-nil,\nasks whether processes should be killed.\nRuns the members of `kill-emacs-query-functions' in turn and stops\nif any returns nil.  If `confirm-kill-emacs' is non-nil, calls it." (interactive "P") #<bytecode 0x22fe93>) nil)
  save-buffers-kill-emacs(nil)
  #f(compiled-function (&optional arg) "Offer to save each buffer, then kill the current connection.\nIf the current frame has no client, kill Emacs itself using\n`save-buffers-kill-emacs'.\n\nWith prefix ARG, silently save all file-visiting buffers, then kill.\n\nIf emacsclient was started with a list of filenames to edit, then\nonly these files will be asked to be saved." (interactive "P") #<bytecode 0x22ff63>)(nil)
  save-buffers-kill-terminal@auto-compile(#f(compiled-function (&optional arg) "Offer to save each buffer, then kill the current connection.\nIf the current frame has no client, kill Emacs itself using\n`save-buffers-kill-emacs'.\n\nWith prefix ARG, silently save all file-visiting buffers, then kill.\n\nIf emacsclient was started with a list of filenames to edit, then\nonly these files will be asked to be saved." (interactive "P") #<bytecode 0x22ff63>) nil)
  apply(save-buffers-kill-terminal@auto-compile #f(compiled-function (&optional arg) "Offer to save each buffer, then kill the current connection.\nIf the current frame has no client, kill Emacs itself using\n`save-buffers-kill-emacs'.\n\nWith prefix ARG, silently save all file-visiting buffers, then kill.\n\nIf emacsclient was started with a list of filenames to edit, then\nonly these files will be asked to be saved." (interactive "P") #<bytecode 0x22ff63>) nil)
  save-buffers-kill-terminal(nil)
  funcall-interactively(save-buffers-kill-terminal nil)
  call-interactively(save-buffers-kill-terminal nil nil)
  command-execute(save-buffers-kill-terminal)

If you need more information, please tell me. :)

**Comment by chimay** [comment]
Thanks to report it, should be ok now.
I recently add some control point to be sure everything is working fine.
It came from the hook on emacs exit which tries to save the vars on file. Just added a test to check vars are not nil.
