### ISSUE TITLE
suspicious :init in use-package example in README

### ISSUE THREAD

**Issue by vornado63** [chimay/torus#5]
Hi, 
sorry, it's me again.. ;)

Could you please verify the use-package example from the README.
Afaik, the code in :init is executed before the package is loaded, so to me torus-init does not make sense there.
In my setup, i put torus-init in the :config part, since this is executed after the package is loaded.

Another idea for updating the use-package example (i use different user-emacs-dirs for package testing):
```
(torus-dirname (concat user-emacs-directory (file-name-as-directory "torus")))
(torus-autoread-file (concat torus-dirname "last.el"))
```
Cheers!

**Comment by chimay** [comment]
You’re right, I checked to be sure it autoreads the last torus file, it works fine.

As for the file/dir vars, I’ll let it in plain strings in the config example (for users not used to Lisp), and put your tip in use-package.

Cheers !
