### ISSUE TITLE
Automatically track mark ring changes in torus?

### ISSUE THREAD

**Issue by bollu** [chimay/torus#6]
It would be awesome of `torus` could automatically track changes to the mark ring and global mark ring. That one, one could the torus API to easily move between locations that one has visited :)

Is there some easy way to achieve this? I'm a total emacs noob, and I'm frustrated with how annoying it is to move between locations.

**Comment by chimay** [comment]
hello, torus does not currently track the mark ring, but you can add all the locations you want of the same file in a buffer group, like:

open my-file
go to position 1
add this location to the ring
go to position 2
add this location to the ring
etc

to navigate the (global) mark rings, you can install the Helm package and bind `helm-all-mark-ring` to a convenient key. Let’s say you want to bind it so super-m:

```
 (global-set-key (kbd "s-'") 'helm-all-mark-rings)
```
By the way, if you want a smooth Emacs experience, I strongly recommend you install Helm or another completion plugin.

**Comment by bollu** [comment]
Great, thanks! I was using `counsel` which does not appear to have an equivalent to `helm-all-mark-rings`.
