### ISSUE TITLE
Cannot add locations in the same file

### ISSUE THREAD

**Issue by WorldsEndless** [chimay/torus#7]
When I try to add a second location in the same file with `torus-add-location`, I see an error like:
```
Location myNewTestament.org at line 8976 col 0 already exists in circle scriptures
```

Repeated for any line I move to (the line number updates in the error). The location is not added.

Since there also doesn't seem to be a ready way to update existing locations, this is a real problem.

**Comment by chimay** [comment]
hello,

locations should be updated automatically

your second location, is it close to the first one in the file ?

**Comment by WorldsEndless** [comment]
My first location is about 9000 lines before the second one (it was at the beginning of the file). 

You say locations should be updated automatically -- what does that mean? When does this automatic update occur?

**Comment by chimay** [comment]
Every time you swith to another buffer, it is updated. So, if you want to add a second location of the file to the circle, you should do it before you leave the buffer. In summary:

Go to position 1 ; add location
Go to position 2 ; add location
Then you can alternate with another buffer, just note that position 2 will be updated to the cursor position. If you want to save position 2 as well, just add a third location before you leave the buffer
