### ISSUE TITLE
torus don't persist through emacs reboots

### ISSUE THREAD

**Issue by WorldsEndless** [chimay/torus#8]
If I need to restart my emacs (e.g. when it freezes), I always come back with no torus, circles, or locations. This seems like a major problem, unless I misunderstand the intended use case of Torus.

**Comment by chimay** [comment]
if you wish to enable a persistent torus, you can enable these options:

```
(setq torus-load-on-startup t)
(setq torus-save-on-exit t)

;; Where to auto load & save torus
(setq torus-autoread-file "~/.emacs.d/torus/last.el")
(setq torus-autowrite-file torus-autoread-file)
```
If you have just made a big change, you can also use `torus-write` to save the torus data, in case Emacs crashes.

**Comment by WorldsEndless** [comment]
Ah; I had those on, but didn't know "write" was what I wanted. Incidentally, it's interesting to me that this isn't the default use-case -- it means I mis-apprehended how Torus is expected to be used by default. Apparently much more short-term buffer groups are the expectation?

**Comment by chimay** [comment]
The autoload/autowrite could surprise new users, or perhaps interfere with some MRU plugin, so it is disabled by default. Anyway, I guess people like to choose where the torus data must be saved.

You can use some short-term groups if you want, it depends on your needs. Most of mine are long term ones.
